title: Operate First Community
author: Operate First Authors
logo: https://www.operate-first.cloud/static/opf-logo-b2b74c6d556f96066bf5836da3e43d61.png
execute:
  execute_notebooks: 'off'
repository:
  url: https://github.com/operate-first/community
  path_to_book: .
  branch: main

# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: img/favicon.png
  use_issues_button: true
  use_repository_button: true
